version: '3'

dotenv: ['.env']

tasks:
  migrate:
    - echo "Migrating account bounded context"
    - cd internal/account/infrastructure/migrations && goose up
    - echo "Migrating wallet bounded context"
    - cd internal/wallet/infrastructure/migrations && goose up
    - echo "Migrating profile bounded context"
    - cd internal/profile/infrastructure/migrations && goose up

  goose:
    - goose {{.CLI_ARGS}}

  run:
    - echo "Building dependencies"
    - wire .
    - echo "Starting server"
    - go run .

  build-binary:
    - echo "Building dependencies"
    - wire .
    - echo "Building app..."
    - go build -o HcServer .
    - echo "Binary named HcServer created successfully. You might want to chmod it to an executable."