// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/rs/zerolog/log"
	"github.com/spf13/viper"
	"hc/api/config"
	"hc/api/packet"
	"hc/internal/connection"
	packet2 "hc/internal/packet"
	config2 "hc/pkg/config"
	"sync"
)

import (
	_ "net/http/pprof"
)

// Injectors from wire.go:

func InitializeApp() *App {
	resolver := ProvideRouteResolver()
	wrapFunc := connection.ProvideMiddlewareWrapper()
	frontController := connection.ProvideFrontController(resolver, wrapFunc)
	repository := connection.ProvideSocketRepository(frontController)
	trafficParser := connection.ProvideTrafficParser()
	requestPool := connection.ProvideRequestPool()
	trafficManager := connection.ProvideTrafficManager(repository, trafficParser, requestPool)
	gameSocket := connection.ProvideGameSocket(repository, trafficManager)
	viper := ProvideConfig()
	app := NewApp(gameSocket, viper)
	return app
}

// wire.go:

var AppSet = wire.NewSet(connection.GameServerSet, ProvideRouteResolver,
	ProvideConfig, wire.Bind(new(packet.Resolver), new(*packet2.Resolver)), wire.Bind(new(config.Reader), new(*viper.Viper)),
)

var (
	routeResolver     *packet2.Resolver
	routeResolverOnce sync.Once

	viperInstance *viper.Viper
	viperOnce     sync.Once
)

func ProvideRouteResolver() *packet2.Resolver {
	routeResolverOnce.Do(func() {
		routeResolver = packet2.NewResolver(CollectRoutes())
	})

	return routeResolver
}

func ProvideConfig() *viper.Viper {
	viperOnce.Do(func() {

		v, err := config2.Build(config2.WithEnvFile(".env"), config2.WithConfigDirectory("config/"))

		if err != nil {
			log.Fatal().Msgf("unable to initialize viper: %s", err.Error())
		}

		viperInstance = v
	})

	return viperInstance
}

func NewApp(server *connection.GameSocket, viper2 *viper.Viper) *App {
	return &App{GameServer: server, Config: viper2}
}
