// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"hc/internal/socket"
	"hc/internal/socket/handler"
)

// Injectors from wire.go:

func InitializeApp(addr string) (*App, error) {
	v := NewConnectionHandler()
	packetHandler := NewPacketHandler()
	gameServer := NewSocketServer(addr, v, packetHandler)
	app := NewApp(gameServer, packetHandler)
	return app, nil
}

// wire.go:

func NewSocketServer(addr string, newConnectionHandlers []socket.ConnectionHandlerFunc, packetHandler handler.PacketHandler) *socket.GameServer {
	return socket.NewGameServer(addr, newConnectionHandlers, packetHandler.Handle)
}

func NewConnectionHandler() []socket.ConnectionHandlerFunc {
	return []socket.ConnectionHandlerFunc{handler.SayHelloToClientHandler}
}

func NewPacketHandler() handler.PacketHandler {
	return handler.PacketHandler{}
}

func NewApp(gameServer *socket.GameServer, packetHandler handler.PacketHandler) *App {
	return &App{GameServer: gameServer}
}
