// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"hc/internal/socket"
)

// Injectors from wire.go:

func InitializeApp(addr string) (*App, error) {
	gameServer := NewSocketServer(addr)
	app := NewApp(gameServer)
	return app, nil
}

// wire.go:

func NewSocketServer(addr string) *socket.GameServer {
	return &socket.GameServer{Addr: addr}
}

func NewApp(gameServer *socket.GameServer) *App {
	return &App{GameServer: gameServer}
}
