// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"hc/internal/socket"
)

// Injectors from wire.go:

func InitializeApp(addr string) (*App, error) {
	packetHandler := NewPacketHandler()
	gameServer := NewSocketServer(addr, packetHandler)
	app := NewApp(gameServer, packetHandler)
	return app, nil
}

// wire.go:

func NewSocketServer(addr string, packetHandler socket.PacketHandler) *socket.GameServer {
	return socket.NewGameServer(addr, packetHandler.Handle)
}

func NewPacketHandler() socket.PacketHandler {
	return socket.PacketHandler{}
}

func NewApp(gameServer *socket.GameServer, packetHandler socket.PacketHandler) *App {
	return &App{GameServer: gameServer}
}
