database:
  driver: mysql
  drivers:
    mysql:
      name: mysql
      host: 127.0.0.1
      port: 3306
      user: root
      password: example
      dbname: example
    testing:
      name: sqlite3