// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"hc/pkg/socket"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	repository := socket.ProvideSocketRepository()
	gameServer := socket.ProvideSocketServer(repository)
	app := NewApp(gameServer, repository)
	return app, nil
}

// wire.go:

var AppSet = wire.NewSet(socket.GameServerSet)

func NewApp(gameServer *socket.GameServer, repository *socket.Repository) *App {
	return &App{
		GameServer:       gameServer,
		GameConfigurator: repository,
	}
}
